
## INFORMATION
#----------------------------------------------------------------------------------------------------
info.version=@project.version@
application-description=@project.description@
application-version=@project.version@

## APPLICATION
#----------------------------------------------------------------------------------------------------
server.port=31303
api.prefix=/mail-sender-demo/api
server.error.whitelabel.enabled=true
spring.application.name=MAIL-SENDER-DEMO
spring.main.allow-bean-definition-overriding=true

# CORS
#----------------------------------------------------------------------------------------------------
cors.allowed.origins=*

# LOG
#----------------------------------------------------------------------------------------------------
logging.file=./MAIL-SENDER-DEMO.log

## JAVA MAIL SENDER
#----------------------------------------------------------------------------------------------------
mail-sender.from=no-reply@idpbr.com
mail-sender.to=jereeltondevel@gmail.com

# LOCAL SMTP MAIL SERVER
### Tip: Use a test mail server as the MailHog (see more in docker-series ion GitHub huntercodexs account)
#spring.mail.host=192.168.0.204
#spring.mail.port=31025
#spring.mail.username=huntercodexs@mail.com
#spring.mail.password=
#spring.mail.properties.mail.smtp.auth=false
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000
#spring.mail.properties.mail.smtp.socketFactory.port=31025
#spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

# OFFICE SMTP MAIL SERVER
spring.mail.host=xxx
spring.mail.port=xxx
spring.mail.user=xxx
spring.mail.username=xxx
spring.mail.password=xxx
spring.mail.properties.mail.smtp.ssl=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.socketFactory.port=xxx
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
